### ISSUE TITLE
Input groups?

### ISSUE THREAD

**Issue by smajl** [bodiam/intellij-bootstrap3#16]
Install just to make life easier with input-groups... don't find them... weep silently. :,D

**Comment by bodiam** [comment]
Hi Jan,

Great comment, but I miss your pull request. If you make one, I'll release
a new version immediately.

Thanks, Erik
Op 24 apr. 2015 12:26 schreef "Jan Peša" <notifications@github.com>:

**Comment by smajl** [comment]
I was expecting that kind of reply :D

**Comment by bodiam** [comment]
Well, it's a simple thing to do, so if it would help you, I can help by
releasing a new version quickly.
Op 24 apr. 2015 14:30 schreef "Jan Peša" <notifications@github.com>:

**Comment by smajl** [comment]
Well, I wish I could help now, but my time schedule is absolutely full at the moment. It's not critical, but input groups would make a nice addition. When I will have more free time and this is not still here, I will try to make a PR.
