### ISSUE TITLE
Bootstrap 3 snippets supported in jade files

### ISSUE THREAD

**Issue by lihaibh** [bodiam/intellij-bootstrap3#18]
@bodiam mark it as improvement.
I added also 'develop' branch and feature branch, should i push both branches here? than make a pull request?

**Comment by bodiam** [comment]
Hi @lihaibh, I think pushing the feature branch should be good enough, right?

**Comment by lihaibh** [comment]
Best practice is to have both master and develop branches.
But its a small library so its not so important.

**Comment by bodiam** [comment]
That's not a best practice, but it's a possible way of doing things. I'm using GitHub flow for all my projects, and there's not both a develop and master branch, but a master and features branches instead. You can read more about it here: https://guides.github.com/introduction/flow/

**Comment by pjedwabny** [comment]
Hello,
I have written small script that converts snippets to Jade. I would like to discuss it.

I've also found that it is impossible to have two snippets with same abbreviation (with disjunctive contexts) in one template group.

https://gist.github.com/pjedwabny/14e1a5d0988435da5b1e
https://gist.github.com/pjedwabny/08b077599adbe4c28a2a

**Comment by bodiam** [comment]
Hello @pjedwabny, that looks very nice! If you can create a Bootstrap template file with both the JADE and the HTML versions, that would be awesome, and I'll make a 2.0 release for that!

**Comment by lihaibh** [comment]
It's not possible to have both jade and html versions of the same snippets under the same group.
By the way that's really cool script. Just wasted time creating the snippets manually heh.

**Comment by bodiam** [comment]
Hi guys, I added the new templates to the Bootstrap plugin. Now it works for Jade as well as the normal HTML version. I'll release a 2.0 version based on this, if everyone is okay with that?

**Comment by pjedwabny** [comment]
Of course its ok, but how did you organized templates? New template group? I'm curious how to do that in elegant way.

**Comment by bodiam** [comment]
I created a new file, Bootstrap3-jade.xml, registered it in Bootstrap3TemplatesProvider, and changed the templateSet group to be Bootstrap3Jade. Tested it, and that seems to work fine.

**Comment by pjedwabny** [comment]
Please, here you have FontAwesome.
https://gist.github.com/pjedwabny/b8ce46f45f82060220b4

I also found https://github.com/haml/html2haml :]

**Comment by bodiam** [comment]
Super! I like this collaboration! :-)

**Comment by pjedwabny** [comment]
In the evening, I will try to make my script more user friendly so maybe we get some kind of build tool. I do not know Java build process but I think that few small scripts that converts to jade or haml is enough. Ok?

**Comment by bodiam** [comment]
Yeah, sure, that would be great! I'm doing the same right now with the Groovy scripts, to generate the readme files, and I really don't care in which language you write it :-). Maybe we can do something with codeship.com or teamcity to automatically build the plugin, so we have to maintain only the HTML version or something.

(btw, I'm on a holiday tomorrow for 2 weeks starting tomorrow, so I won't have time to make a new release before that I think)

**Comment by bodiam** [comment]
I'm making a release with the Jade support for Bootstrap and Fontawesome. If you have some extra things to add, please let me know, and I'll make a 2.0.1!
