### ISSUE TITLE
Broken class attribute ( bs3-select:h )

### ISSUE THREAD

**Issue by JesusTheHun** [bodiam/intellij-bootstrap3#20]
Hi there,

With the tag `bs3-select:h` there is a double quote issue on the label class attribute : 

Expected
 
```html
<label for="inputID" class="$var2 control-label">Label:</label>
```

Current result

```html
<label for="inputID" class="$var2" control-label">Label:</label>
```

Note the closing double quote after `$var2`

**Comment by bodiam** [comment]
This one will be fixed in the 2.0.0 version.
