### ISSUE TITLE
CMD+ can't be replaced by CTRL+ (Windows)!

### ISSUE THREAD

**Issue by gildniy** [bodiam/intellij-bootstrap3#21]
Hi,
As we know many times "CMD+" has "CTRL+" as cousin key in Windows. Me am not able to use the "CTRL+J" key for choosing the "bs3-something", have I missed something?

**Comment by gildniy** [comment]
Fixed #21

**Comment by pint12** [comment]
Hi. I am having the same issue . i tried win+j and ctl+j 
I am also using windows
