### ISSUE TITLE
Plugin not auto-completing in webstorm?

### ISSUE THREAD

**Issue by wolfgangersmith** [bodiam/intellij-bootstrap3#22]
Hello,

I've installed and clicked "apply" to this plugin and restarted webstorm, but when i type 'bs3-....'  , I get no prompts nor is the template working when i type in the complete bs3-shortcodes.

What am i missing?

**Comment by noinget** [comment]
You need press ctrl+j

**Comment by wolfgangersmith** [comment]
I missed this!

Plugin is working great,

Thanks

**Comment by bodiam** [comment]
Glad it works!
