### ISSUE TITLE
Intellij 14.1.2

### ISSUE THREAD

**Issue by ahasall** [bodiam/intellij-bootstrap3#25]
I've just installer your plugin but it's not working.
There is no templates associated with bs3

**Comment by bodiam** [comment]
Hi @ahasall , I just updated myself to the newest version, but it works for me. Did you press ctrl/cmd+j? Can you send me a screenshot of the Live Templates settings in the editor?

**Comment by ahasall** [comment]
Thanks for your answer. It's working. I just had to reboot my computer. Restarting Intellij was not sufficient.

**Comment by bodiam** [comment]
Glad to hear it's working!
