### ISSUE TITLE
Bug in bs3-modal snippet

### ISSUE THREAD

**Issue by vibhanshuc** [bodiam/intellij-bootstrap3#27]
in bs3-modal snippet 
HTML for trigger button is
    `<a class="btn btn-primary" data-toggle="modal" href="modal-id">Trigger modal</a>`

value of href attribute should have been `#modal-id`
    `<a class="btn btn-primary" data-toggle="modal" href="#modal-id">Trigger modal</a>`

**Comment by bodiam** [comment]
I'm not sure why the href should be #model-id, but the href model-id is incorrect for sure. I think I'll change it to #, would that work too?

**Comment by vibhanshu86** [comment]
yes it would work for sure.

**Comment by fcools** [comment]
Although it isn't wrong to use an anchor for triggering the modal, why not making use of a button as the bootstrap documentation and examples?
```<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Trigger modal</button>```

**Comment by bodiam** [comment]
Good suggestion. I'll look into it!
