### ISSUE TITLE
bs3-template:html5 content

### ISSUE THREAD

**Issue by fcools** [bodiam/intellij-bootstrap3#31]
Can the html document header bs3-template:html5 be like it's provided on http://getbootstrap.com/getting-started/?

**Comment by bodiam** [comment]
Sure can. Can you make a contribution?

**Comment by fcools** [comment]
Ok, I'll fork it and look into it tonight.
While I'm at it, you want some other changes?

**Comment by bodiam** [comment]
Well, if you have some good ideas, I'm open to anything!

**Comment by bodiam** [comment]
No feedback.

**Comment by fcools** [comment]
I've made a pull request a long time ago.

**Comment by bodiam** [comment]
Oh, I'm very sorry! It's merged for a long time already, I forgot to close this issue! My apologies!

**Comment by fcools** [comment]
No problem. 😉
Just keep up the good work. 😁



Met vriendelijke groet,

Ferry Cools
