### ISSUE TITLE
PHPStorm 8.0.3

### ISSUE THREAD

**Issue by nick-harper** [bodiam/intellij-bootstrap3#36]
I have installed the plugin in PHPStorm, but when I type bs3- and then cmd-J I just get a full list of html commands.

It is definately installed and in the list of plugins ok?

**Comment by bodiam** [comment]
I cannot reproduce this, it works on my PHP storm, and, when I look at the usage of the plugin, 50.000 people use it. Could it be you're missing something?

**Comment by ivelrrat** [comment]
Same thing for me. I'm in PHPStorm 9.0.2 though.

I downloaded version 2.1 again and that is working for me.

 https://plugins.jetbrains.com/plugin/7572?pr=phpStorm&showAllUpdates=true

**Comment by ivelrrat** [comment]
I finally got more time to look into this and I reinstalled PhpStorm with "Mac OS X 10.10+ w/ bundled JDK 1.8" version and it is now working fine. My previous PhpStorm install had JDK 1.6 the default apple version.

**Comment by bodiam** [comment]
Strange, that shouldn't have any effect I guess, but I'm glad it's working!
