### ISSUE TITLE
Tab not working while Ctrl J works fine

### ISSUE THREAD

**Issue by stevehomer** [bodiam/intellij-bootstrap3#39]
If I type bs3 and hit tab I just get pair of <bs3> tags. If I hit Ctrl J I get the normal full list.

If I type bs3-alert and hit tab works fine.

(Not sure if this is dupe of #36 as that seems to be missing the opening sentence)
Running latest BS3 and phpS

EDIT: Also when I insert code get tabs not spaces for indents. May be something I have set in settings but cannot find it.

**Comment by bodiam** [comment]
Hi @stevehomer , I heard this before, but this is not an issue in the plugin, and certainly outside my control. You might check the IntelliJ issue tracker or maybe checkout the solution of #36 ?
