### ISSUE TITLE
Snippets do not show

### ISSUE THREAD

**Issue by jcastillotx** [bodiam/intellij-bootstrap3#42]
I am running IntelliJ IDEA 15.03 and I have Bootstrap 3 installed but I cannot get any of the snippets to show with bs3- cmd+j.

**Comment by bodiam** [comment]
Try to reinstall or restart IntelliJ, that will fix it. This has been reported quite often now, but the plugin works.

**Comment by jcastillotx** [comment]
Restarted and reinstalled and still not showing any snippets. Trying to figure why.

**Comment by bodiam** [comment]
If you're going to Settings -> Editor -> Live templates, do you see the Bootstrap section there?

**Comment by jcastillotx** [comment]
Does not show anything there

**Comment by jcastillotx** [comment]
<img width="1680" alt="screen shot 2016-02-06 at 7 12 00 pm" src="https://cloud.githubusercontent.com/assets/305466/12867233/c22ef028-cd05-11e5-9206-efe1662fd1a5.png">
![Uploading Screen Shot 2016-02-06 at 7.12.34 PM.png…]()

**Comment by jcastillotx** [comment]
<img width="1680" alt="screen shot 2016-02-06 at 7 12 34 pm" src="https://cloud.githubusercontent.com/assets/305466/12867244/ed7ee526-cd05-11e5-973e-def2a37ce3a7.png">

**Comment by jcastillotx** [comment]
<img width="1680" alt="screen shot 2016-02-06 at 7 16 08 pm" src="https://cloud.githubusercontent.com/assets/305466/12867250/176c5634-cd06-11e5-8944-ba7d3d0e15b5.png">

**Comment by bodiam** [comment]
Very interesting. It looks good. How about File -> Invalidate Caches and Restart?

**Comment by jcastillotx** [comment]
no love.

**Comment by bodiam** [comment]
I'm sorry, then I don't know how to make it work. The only workaround I could think of is checking this place: cd ~/Library/Preferences/IntelliJIdea15/templates/ , stop IntelliJ, put the Bootstrap3.xml there, start IntelliJ, and check what happens then. It's not ideal, but I'm curious if it works.

**Comment by jcastillotx** [comment]
That worked.

**Comment by arttema** [comment]
It's the same for me. Intellij14. but putting xml worked. Great work though. thanks!
