### ISSUE TITLE
Mixed indentations (some tabs, some spaces)

### ISSUE THREAD

**Issue by ifdattic** [bodiam/intellij-bootstrap3#44]
The snippets have different indentations, some of them use tabs (e.g., `bs3-alert`) some of them use spaces (e.g., `bs3-alert-link`). After closer consideration event those snippets that use spaces, don't have a correct amount of spaces (some have 2, `bs3-media-object` some have 4).

**Comment by bodiam** [comment]
Thanks for reporting it. If you want to fix it, that's cool, then I'll release a new version.

**Comment by azeemhassni** [comment]
Why don't we set `toReformat` attribute to `true` to allow the Live Templates adopt whatever code style the user uses.

**Comment by chrishessler** [comment]
I can see this issue is still open, but has someone found a solution or work-around for this issue?

I would really like to have it adopt to my code style (tab with size 4) instead of having to reformat the snippets every time I use one..

**Comment by bodiam** [comment]
I think setting the reformat to true should fix it, however, I'm not sure
which templates are missing this (I thought I enabled it for all, but
apparently not). Would it be possible for you to try it out, and do a pull
request? I wouldn't mind releasing a new version then.

Cheers,
Erik
