### ISSUE TITLE
does not work on my phpstorm 9 and Mac

### ISSUE THREAD

**Issue by xklake** [bodiam/intellij-bootstrap3#45]
anybody else having the same issue?

**Comment by moesphemie** [comment]
How did you install the plugin?
Did you restart pstorm after the Install?

**Comment by louruixiao** [comment]
IDE is intellij idea14 on mac.
the plugin has been installed,ide has been restart,but the plugin still does't work.
i need some help!!!

**Comment by xklake** [comment]
i gave up after tried different ways. 

Date: Thu, 20 Oct 2016 20:21:14 -0700

**Comment by moesphemie** [comment]
Here you get a screenshot of my settings.
I've installed the bootstrap 3 from Settings > Plugins > Browse repositories
After that i've restarted pStorm and opened a HTML scratch file. 
The Templates work fine here. Make sure they are applicable in the language you use.

I'm using the latest version of PHPStorm (2016.2) – Maybe there is a problem with your version?

![bildschirmfoto 2016-10-25 um 20 56 48](https://cloud.githubusercontent.com/assets/11868007/19699972/aa109f00-9af5-11e6-904a-92acfaea4440.png)
