### ISSUE TITLE
The pulgin does work only in  the quotation mark ("")

### ISSUE THREAD

**Issue by shadirok** [bodiam/intellij-bootstrap3#52]
The autocomplete does work fine only in the quotation mark ("")
e.g. `<div class="_when i satrt writing here_"> </div>`

when i try to write some where else in blnak HTML file, it does not work.

Thank you

**Comment by bodiam** [comment]
Hi Shadirok, thanks for the message. What you should try is to type "bs3-",
and then press CMD+J (or Ctrl+J). That should bring up the templates!

**Comment by shadirok** [comment]
its working thank you,
Is there any way to make it (configuration) directly without click( Ctrl+J) 
im using Intilij

**Comment by bodiam** [comment]
Not that I know off (it's an IntelliJ thing mostly), but you could also
type "bs3" and then followed by ctrl+space. That might be a bit easier?

**Comment by shadirok** [comment]
Thank you very much.
Have a nice day.
