### ISSUE TITLE
Bootstrap plugin doesn't work in HTML files.

### ISSUE THREAD

**Issue by lihaibh** [bodiam/intellij-bootstrap3#7]
I used this plugin on PhpStorm however it seems like the auto completion is working only inside <?php ?> scope and when im trying to use it in an html file or blade (laravel blade) file it doesn't seem to work.

**Comment by holozip** [comment]
With me being a WebStorm noob, I hadn't previously used templates. The cmd+j comment above helped a lot. It may be worth adding to the instructions to help other folks as the screen cast doesn't show the keypresses used.

Great plugin, props for the work you've put into this. :-)

**Comment by bodiam** [comment]
Hi @holozip , thanks for the feedback. I've added some usage instructions to the Readme file!

**Comment by lihaibh** [comment]
@bodiam is there any way to make it work also with jade files? because ive started to compile jade to html and I think it will be really helpful.

**Comment by bodiam** [comment]
I'm sure that's possible, but it would probably mean changing all the templates to jade right? That might be a bit tricky.

**Comment by lihaibh** [comment]
You mean add more templates compatible with .jade files.
I can open feature and make a pull request if you want.

**Comment by bodiam** [comment]
Well, that would be awesome if you could do that. If you can do a pull request, I'll for sure create a new version!

**Comment by lihaibh** [comment]
I opened branch im starting to work on it.
Can you share with me how you created the boostrap3.jar fuke?
I guess the "jar" file is the compiled file that u can import to Webstorm/Phpstorm IDE right? how did you compile the library into that file?

**Comment by bodiam** [comment]
Wow, that's quick! To create the plugin, I always right click on the project name in the project view, and then do 'Prepare Plugin for deployment'. However, that's only needed when uploading the plugin: to test the plugin, I just use a run configuration of type Plugin, which starts up a community version of IntelliJ, in which I test the plugin. Hope that helps!

**Comment by lihaibh** [comment]
To test i just compile jade to html and compare against static html that in which i used your snippets XD
