### ISSUE TITLE
Would be nice to have a template to insert Bootstrap from the CDN

### ISSUE THREAD

**Issue by clarkedesign** [bodiam/intellij-bootstrap3#9]
could we have a Insert Bootstrap from CDN template please say "bs3-cdn" to insert something like the below. Maybe minified and not-minified ?

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

**Comment by bodiam** [comment]
Hi @clarkedesign , I'm sure sure what you mean. Could you please explain what you are looking for? Are the current bs3-cdn templates not good enough?
